/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CardComponent {
        "content": string;
        "name": string;
        "years": number;
    }
    interface FooterComponent {
        "link": string;
        "mainTitle": string;
        "subtitle": string;
    }
    interface HeaderComponent {
        "mainTitle": string;
        "open": () => Promise<void>;
    }
    interface PictureComponent {
        "type": string;
        "url": string;
    }
}
declare global {
    interface HTMLCardComponentElement extends Components.CardComponent, HTMLStencilElement {
    }
    var HTMLCardComponentElement: {
        prototype: HTMLCardComponentElement;
        new (): HTMLCardComponentElement;
    };
    interface HTMLFooterComponentElement extends Components.FooterComponent, HTMLStencilElement {
    }
    var HTMLFooterComponentElement: {
        prototype: HTMLFooterComponentElement;
        new (): HTMLFooterComponentElement;
    };
    interface HTMLHeaderComponentElement extends Components.HeaderComponent, HTMLStencilElement {
    }
    var HTMLHeaderComponentElement: {
        prototype: HTMLHeaderComponentElement;
        new (): HTMLHeaderComponentElement;
    };
    interface HTMLPictureComponentElement extends Components.PictureComponent, HTMLStencilElement {
    }
    var HTMLPictureComponentElement: {
        prototype: HTMLPictureComponentElement;
        new (): HTMLPictureComponentElement;
    };
    interface HTMLElementTagNameMap {
        "card-component": HTMLCardComponentElement;
        "footer-component": HTMLFooterComponentElement;
        "header-component": HTMLHeaderComponentElement;
        "picture-component": HTMLPictureComponentElement;
    }
}
declare namespace LocalJSX {
    interface CardComponent {
        "content"?: string;
        "name"?: string;
        "years"?: number;
    }
    interface FooterComponent {
        "link"?: string;
        "mainTitle"?: string;
        "subtitle"?: string;
    }
    interface HeaderComponent {
        "mainTitle"?: string;
    }
    interface PictureComponent {
        "type"?: string;
        "url"?: string;
    }
    interface IntrinsicElements {
        "card-component": CardComponent;
        "footer-component": FooterComponent;
        "header-component": HeaderComponent;
        "picture-component": PictureComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-component": LocalJSX.CardComponent & JSXBase.HTMLAttributes<HTMLCardComponentElement>;
            "footer-component": LocalJSX.FooterComponent & JSXBase.HTMLAttributes<HTMLFooterComponentElement>;
            "header-component": LocalJSX.HeaderComponent & JSXBase.HTMLAttributes<HTMLHeaderComponentElement>;
            "picture-component": LocalJSX.PictureComponent & JSXBase.HTMLAttributes<HTMLPictureComponentElement>;
        }
    }
}
